# Generated by Django 6.0.2 on 2026-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('GO', 'Golang'), ('SQ', 'SQL'), ('OT', 'Other')], default='PY', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
