# Generated by Django 6.0.2 on 2026-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_language_alter_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('PY', 'Python'), ('GO', 'Golang'), ('SQ', 'SQL'), ('OT', 'Other')], default='PY', max_length=2),
        ),
    ]
