# Generated by Django 6.0.2 on 2026-02-22 14:24

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['top', 'center'], force_format=None, keep_meta=True, quality=-1, scale=None, size=[425, 225], upload_to='thumbnails'),
        ),
    ]
