# Generated by Django 6.0.2 on 2026-02-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectimage_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='project',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectimage'),
            preserve_default=False,
        ),
    ]
