# Generated by Django 6.0.2 on 2026-02-22 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_rename_project_projectimage_title_project_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectimage'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project'),
        ),
    ]
