# Generated by Django 6.0.7 on 2026-07-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_images_alter_projectimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
